SELECT TOP 20 * FROM customer

--total revenue generated by male vs female 
select gender, SUM(purchase_amount) as revenue
from customer
group by Gender

--customers used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--top 5 products with the highest avg review rating
select TOP 5 item_purchased, ROUND(AVG(review_rating),2) as "Avg Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc

--avg purchase amounts between standard and express shipping
select shipping_type, AVG(purchase_amount) as "Avg purchase amount"
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--compare avg spend and total revenue between subscribers and non-subscribers
select Count(customer_id) as total_customers,
subscription_status,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue desc

--top 5 products with highest percentage of purchases with discounts applied
select TOP 5 item_purchased,
100 * SUM(case when discount_applied = 'Yes' then 1 else 0 end)/COUNT(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--segment customers into new, returning, and loyal based on their total number of pervious purchases and show count of each segment
with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

--top 3 most purchased products within each category
with item_counts as(
select category, item_purchased, COUNT(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

-- customers who are repeat buyers (more than 5 previous purchases) also likey to subscribe?
select subscription_status, COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--revenue contribution of each age group
select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc